# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Unit tests on iPhone 16 Plus simulator"
  lane :test do
    run_tests(
        project: "iosApp.xcodeproj",
        scheme: "weatherAppTests",
        sdk: "iphonesimulator",
        devices: ["iPhone 16 Plus"],
        derived_data_path: "build",
    )
  end
end
