name: WeatherApp CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'composeApp'
      - name: Run Android tests
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'test'
          subdirectory: 'composeApp'
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'iosApp'
      - name: Run iOS tests
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'test'
          subdirectory: 'iosApp'
