name: Weather App Develop CI

on:
  push:
    branches: [ "main", "develop", "feature/*", "bugfix/*" ]

jobs:
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode secrets
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $GITHUB_WORKSPACE/weatherapp-release-upload-keystore.jks
          echo "$SECRETS_FILE" > $GITHUB_WORKSPACE/secrets.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SECRETS_FILE: ${{ secrets.SECRETS_FILE }}

      - name: Detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: |
          ./gradlew \
            kotlinUpgradeYarnLock \
            build

      - name: Check
        run: ./gradlew check

      # Upload test reports as an artifact
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/build/reports/tests/**'

  run-android-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: run connectedAndroidTest
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 5
          test-suite: connectedCheck
          cmd: ./gradlew :composeApp:connectedAndroidTest

  run-ios-tests:
    runs-on: macos-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run iOS Simulator Tests
        run: ./gradlew :composeApp:iosSimulatorArm64Test
